name: flutter_hanoi
description: flutter hanoi tower
publish_to: 'none' 

version: 0.3.1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  confetti: ^0.7.0
  cool_dropdown: ^2.1.0
  flutter:
    sdk: flutter
  flutter_switch: ^0.3.2
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

